### PR TITLE
fix: rectify ciphers compliance check

### LINKED ISSUE #39: tls_ciphers and tls_cipher_strength always omitted but used in compliance checks
Noticed the compliance checks was still using tls_ciphers to determine compliance, but it seems that was something maybe filled in by nmap before the testssl migration.

Also noticed tls_cipher_strength is never provided - guessing that was nmap too.

Propose:

Remove tls_cipher_strength — zero risk, nothing fills it.

Keep tls_ciphers on PortResult but populate it from forward_secrecy.ecdhe in the current flow. It's the right semantic field ("what ciphers does this endpoint offer"). The source changes when the tool changes, but the field stays.

For the future:

Thinking maybe it would be best to setup some kind of adapter pattern in the future so that any tool could be leveraged.

### PR DESCRIPTION
**Pull request by damdo**
- [fix: complete IANA-to-OpenSSL cipher map and fix incorrect mappings](https://github.com/openshift/tls-scanner/pull/41/changes/3198edcfcd27ac140b6b0b460ba6c16b62529b34) 
    The `IanaCipherToOpenSSLCipherMap` had two problems preventing cipher compliance from passing:
    - Several mappings pointed to wrong OpenSSL names (e.g. `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` mapped to `TLS_AES_128_GCM_SHA256` instead of `ECDHE-RSA-AES128-GCM-SHA256`), and identity entries (OpenSSL -> OpenSSL) not aligned with the IANA-to-OpenSSL purpose.
    - Ciphers from OpenShift TLS profile (Old, Intermediate, Modern) were missing IANA entries, so any endpoint offering those ciphers would fail compliance when reported in IANA format.
    Clean the map to contain only genuine `IANA -> OpenSSL` translations covering all ciphers across all three profiles.
    In `checkCipherCompliance`, fall back to using the cipher name as-is when no IANA mapping exists (`testssl.sh` already reports in `OpenSSL` format via `FS_ECDHE`),
    and log a warning when a cipher is not found in the expected set.

- [fix: populate TlsCiphers from testssl.sh key exchange data](https://github.com/openshift/tls-scanner/pull/41/changes/1e40b80b33309ea8cfdb6e1a225849a5170d3bd2) 
    Cipher compliance (ciphers field in `*_tls_config_compliance`) always returned false
    because `TlsCiphers` was never populated after the nmap-to-testssl.sh migration.
    The cipher data was successfully extracted into `TlsKeyExchange.ForwardSecrecy.ECDHE`
    but never wired back to `TlsCiphers`, so `checkCipherCompliance` always received an empty slice.
    Wire `TlsCiphers` from `ForwardSecrecy.ECDHE` in `batchScan` and remove
    the dead `TlsCipherStrength` field (nmap leftover, never populated by testssl.sh).

- [fix: extract ciphers from cipher-tls1_* findings instead of FS_ECDHE](https://github.com/openshift/tls-scanner/pull/41/changes/0f803addcaf7adf333c409bee1f062cb9206b4ef)
    TlsCiphers was populated from FS_ECDHE which only contains TLS 1.2
    forward-secrecy ciphers. TLS 1.3 ciphers and non-FS suites (e.g.
    static RSA key exchange) were silently excluded from compliance checks.
    Add ExtractCiphersFromTestSSL which parses cipher-tls1_2_* and
    cipher-tls1_3_* findings directly, capturing every cipher the server
    offers regardless of key exchange type. Replace the FS_ECDHE workaround
    in batchScan with this new extraction.

Fixes #39

### CODE REVIEW

File: internal/scanner/scanner.go [hunk 1]
```diff
@@ -356,8 +356,11 @@ func batchScan(jobs []ScanJob, concurrentScans int, client *k8s.Client, tlsConfi
 			Service:  "ssl/tls",
 		}
 
-		portResult.TlsVersions, portResult.TlsCiphers, portResult.TlsCipherStrength = ExtractTLSInfo(scanResult)
+		portResult.TlsVersions, _ = ExtractTLSInfo(scanResult)
 		portResult.TlsKeyExchange = ExtractKeyExchangeFromTestSSL(portData)
+		if portResult.TlsKeyExchange != nil && portResult.TlsKeyExchange.ForwardSecrecy != nil {
+			portResult.TlsCiphers = portResult.TlsKeyExchange.ForwardSecrecy.ECDHE
```
Comment (smith-xyz) [inline internal/scanner/scanner.go]: this may be fine in practice, but FS_ECDHE / FS_ciphers from testssl.sh only reports forward-secrecy cipher suites AFAIK. If a server offers non-FS ciphers (e.g., AES128-GCM-SHA256 with RSA key exchange), they won't appear in TlsCiphers.  

Again, maybe fine but it is a silent gap.

Comment (smith-xyz) [inline internal/scanner/scanner.go]: TlsCiphers as a field name suggests completeness imo. Its fine but maybe worth noting that I don't think TLS 1.3 ciphers are reported in FS_ECDHE. So really this property is just to catch the tls 1.2 ciphers for compliance checking?

File: internal/scanner/testssl.go [hunk 2]
```diff
@@ -350,36 +348,13 @@ func ExtractTLSInfo(scanRun ScanRun) (versions []string, ciphers []string, ciphe
...
 				}
 			}
 		}
 	}
 
-	allDetectedCiphers = removeDuplicates(allDetectedCiphers)
 	tlsVersions = removeDuplicates(tlsVersions)
 
-	return tlsVersions, allDetectedCiphers, cipherStrength
+	return tlsVersions, nil
```
Comment (smith-xyz) [inline internal/scanner/testssl.go]: is the return for ciphers dead code?

**Comment by smith-xyz** [comment]
@damdo see my comments - nothing really blocking we could merge it in as is, seems to fix the issue

File: internal/scanner/testssl.go (hunk 2 above)
Comment (damdo) [reply internal/scanner/testssl.go]: Fixed to only return the tlsversion

File: internal/scanner/scanner.go (hunk 1 above)
Comment (damdo) [reply internal/scanner/scanner.go]: Agree. Added a commit to extract all ciphers from `cipher-tls1_*` instead of just the forward secrecy ones.

Comment (damdo) [reply internal/scanner/scanner.go]: Agree. Added a commit to extract all ciphers from `cipher-tls1_*` instead of just the forward secrecy ones.

**Comment by ingvagabund** [comment]
Checking the tls-scanner artifacts from the latest CI job in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_tls-scanner/41/pull-ci-openshift-tls-scanner-main-tls13-conformance/2040046236580450304/artifacts/tls13-conformance/tls-scanner-run/artifacts/tls-scanner/results.json I still don't see `tls_ciphers` field set in the `port_results` map. Is the job testing the latest changes? I'd expect it to be set after https://github.com/openshift/tls-scanner/pull/41/commits/1e40b80b33309ea8cfdb6e1a225849a5170d3bd2#diff-95e0a286796962f784af743a32471dada7258c4789b441aaca0a77653e3c1155R362 change. Given the produced json has e.g. this (for `openshift-kube-scheduler-operator-868d647944-cn4vf` pod):
```
      "port_results": [
        {
          ...
          "tls_versions": [
            "TLSv1.2",
            "TLSv1.3"
          ],
          "tls_key_exchange": {
            "forward_secrecy": {
              "supported": true,
              "ecdhe": [
                "TLS_AES_256_GCM_SHA384",
                "TLS_CHACHA20_POLY1305_SHA256",
                "ECDHE-RSA-AES256-GCM-SHA384",
                "ECDHE-RSA-CHACHA20-POLY1305",
                "TLS_AES_128_GCM_SHA256",
                "ECDHE-RSA-AES128-GCM-SHA256"
              ],
              ...
            }
          },
          ...
        }
      ],
      ...
      "pod": {
        "Name": "openshift-kube-scheduler-operator-868d647944-cn4vf",
```

`tls_key_exchange.forward_secrecy.ecdhe` has non-empty list. So https://github.com/openshift/tls-scanner/pull/41/commits/1e40b80b33309ea8cfdb6e1a225849a5170d3bd2#diff-95e0a286796962f784af743a32471dada7258c4789b441aaca0a77653e3c1155R362 change is expected to produce non-empty list for `tls_ciphers`.

**Comment by ingvagabund** [comment]
Running a patched version on top of this PR with `--namespace-filter=openshift-kube-scheduler-operator` added into the job template. The following findings is produced:
```json
[{"finding":"10.129.0.37:8443 appears to support TLS 1.3 ONLY, switching from timeout --preserve-status 5 /opt/testssl/bin/openssl.Linux.x86_64 to /usr/bin/openssl automagically","id":"optimal_proto","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"No engine or GOST support via engine with your /usr/bin/openssl","id":"engine_problem","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"WARN"},{"finding":"HTTP","id":"service","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"No 128 cipher limit bug","id":"pre_128cipher","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"not offered","id":"SSLv2","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"finding":"not offered","id":"SSLv3","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"finding":"not offered","id":"TLS1","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"not offered","id":"TLS1_1","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"not offered","id":"TLS1_2","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"offered with final","id":"TLS1_3","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"finding":"not possible for TLS 1.3-only hosts","id":"NPN","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"WARN"},{"finding":"http/1.1","id":"ALPN","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"cwe":"CWE-327","finding":"not offered","id":"cipherlist_NULL","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"cwe":"CWE-327","finding":"not offered","id":"cipherlist_aNULL","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"cwe":"CWE-327","finding":"not offered","id":"cipherlist_EXPORT","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"cwe":"CWE-327","finding":"not offered","id":"cipherlist_LOW","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"cwe":"CWE-310","finding":"not offered","id":"cipherlist_3DES_IDEA","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"cwe":"CWE-310","finding":"not offered","id":"cipherlist_OBSOLETED","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"not offered","id":"cipherlist_STRONG_NOFS","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"offered","id":"cipherlist_STRONG_FS","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"finding":"offered","id":"FS","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"finding":"TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256","id":"FS_ciphers","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"},{"finding":"X25519MLKEM768","id":"FS_KEMs","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"finding":"prime256v1 secp384r1 secp521r1 X25519","id":"FS_ECDHE_curves","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"OK"},{"finding":"RSA-PSS-RSAE+SHA512 RSA-PSS-RSAE+SHA384 RSA-PSS-RSAE+SHA256","id":"FS_TLS13_sig_algs","ip":"10.129.0.37/10.129.0.37","port":"8443","severity":"INFO"}]
```

Following the changes in `ExtractCiphersFromTestSSL` there's unfortunately no id prefixed with `cipher-tls1_` key. Thus, the list of ciphers is always empty.

EDIT: https://github.com/openshift/tls-scanner/pull/41#discussion_r3051438584 has more details about how to make the mentioned findings appear.

File: internal/scanner/scanner.go (hunk 1 above)
Comment (ingvagabund) [reply internal/scanner/scanner.go]: Is it guaranteed `cipher-tls1_*` prefixed id will always be present? Running tls-scanner on top of this PR with -`--namespace-filter=openshift-kube-scheduler-operator` set does not produce any such finding. Even though the list of ciphers is set to the Modern one. From the tls config for the operator:
```yaml
$ cat /var/run/configmaps/config/config.yaml 
apiVersion: operator.openshift.io/v1alpha1
kind: GenericOperatorConfig
servingInfo:
  cipherSuites:
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  - TLS_CHACHA20_POLY1305_SHA256
  minTLSVersion: VersionTLS13
```

Comment (ingvagabund) [reply internal/scanner/scanner.go]: Running `testtsl.sh` with extra `-E` option helps:
```json
{
    "finding": "TLS 1.3   x1302   TLS_AES_256_GCM_SHA384            ECDH/MLKEM AESGCM      256      TLS_AES_256_GCM_SHA384",
    "id": "cipher-tls1_3_x1302",
    "ip": "10.129.0.37/10.129.0.37",
    "port": "8443",
    "severity": "OK"
  },
  {
    "finding": "TLS 1.3   x1303   TLS_CHACHA20_POLY1305_SHA256      ECDH/MLKEM ChaCha20    256      TLS_CHACHA20_POLY1305_SHA256",
    "id": "cipher-tls1_3_x1303",
    "ip": "10.129.0.37/10.129.0.37",
    "port": "8443",
    "severity": "OK"
  },
  {
    "finding": "TLS 1.3   x1301   TLS_AES_128_GCM_SHA256            ECDH/MLKEM AESGCM      128      TLS_AES_128_GCM_SHA256",
    "id": "cipher-tls1_3_x1301",
    "ip": "10.129.0.37/10.129.0.37",
    "port": "8443",
    "severity": "OK"
  },
```

Is this the expected list of findings?

Comment (ingvagabund) [reply internal/scanner/scanner.go]: The scan report produces this:
```json
          "tls_versions": [
            "TLSv1.3"
          ],
          "tls_ciphers": [
            "TLS 1.3   x1302   TLS_AES_256_GCM_SHA384            ECDH/MLKEM AESGCM      256      TLS_AES_256_GCM_SHA384",
            "TLS 1.3   x1303   TLS_CHACHA20_POLY1305_SHA256      ECDH/MLKEM ChaCha20    256      TLS_CHACHA20_POLY1305_SHA256",
            "TLS 1.3   x1301   TLS_AES_128_GCM_SHA256            ECDH/MLKEM AESGCM      128      TLS_AES_128_GCM_SHA256"
          ],
```
which is not in the right format. The code under `checkCipherCompliance` expects a list of ciphers. I.e. `["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256", "TLS_AES_128_GCM_SHA256"]` instead.

Comment (ingvagabund) [reply internal/scanner/scanner.go]: That finding is produced by https://github.com/testssl/testssl.sh/blob/3.2/testssl.sh#L7716-L7717:
```bash
                    id="cipher-${proto}_${normalized_hexcode[i]}"
                    fileout "$id" "$(get_cipher_quality_severity "${ciph[i]}")" "$proto_text  $(neat_list "${normalized_hexcode[i]}" "${ciph[i]}" "${kx[i]}" "${enc[i]}" "${export2[i]}")"
```
The produced "finding" value has the constructed format from
```bash
"$proto_text  $(neat_list "${normalized_hexcode[i]}" "${ciph[i]}" "${kx[i]}" "${enc[i]}" "${export2[i]}")"
```
So unless the script gets updated and changes the format the produced `"${ciph[i]}"` value can be read.

Comment (ingvagabund) [reply internal/scanner/scanner.go]: PoC code updates in https://github.com/openshift/tls-scanner/pull/42

**Comment by damdo** [comment]
Hey @ingvagabund I've added your commit from #41 here.

**Review by smith-xyz — APPROVED** [review]

**Comment by ingvagabund** [comment]
LGTM
